/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _1_calc_fibonacci_1_opaque_NodeStruct ;
struct _1_generate_license_key_1_opaque_NodeStruct ;
struct _1_main_1_opaque_NodeStruct ;
struct _1_mult_chars_1_opaque_NodeStruct ;
struct _IO_FILE ;
struct timeval ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
char **_global_argv  =    (char **)0;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
extern int getpagesize() ;
struct _1_calc_fibonacci_1_opaque_NodeStruct {
   struct _1_calc_fibonacci_1_opaque_NodeStruct *prev ;
   int data ;
   struct _1_calc_fibonacci_1_opaque_NodeStruct *next ;
};
struct _1_calc_fibonacci_1_opaque_NodeStruct *_1_calc_fibonacci_1_opaque_ptr_2  =    (struct _1_calc_fibonacci_1_opaque_NodeStruct *)0;
struct _1_generate_license_key_1_opaque_NodeStruct {
   int data ;
   struct _1_generate_license_key_1_opaque_NodeStruct *next ;
   struct _1_generate_license_key_1_opaque_NodeStruct *prev ;
};
struct _1_generate_license_key_1_opaque_NodeStruct *_1_generate_license_key_1_opaque_list_2  =    (struct _1_generate_license_key_1_opaque_NodeStruct *)0;
struct _1_generate_license_key_1_opaque_NodeStruct *_1_generate_license_key_1_opaque_list_1  =    (struct _1_generate_license_key_1_opaque_NodeStruct *)0;
extern int pthread_join(void *thread ,
                        void **value_ptr ) ;
typedef unsigned long size_t;
extern  __attribute__((__nothrow__)) size_t ( __attribute__((__nonnull__(1), __leaf__)) strlen)(char const   *__s )  __attribute__((__pure__)) ;
extern int open(char const   *filename , int oflag  , ...) ;
struct _1_main_1_opaque_NodeStruct {
   struct _1_main_1_opaque_NodeStruct *next ;
   int data ;
   struct _1_main_1_opaque_NodeStruct *prev ;
};
struct _1_main_1_opaque_NodeStruct *_1_main_1_opaque_list_2  =    (struct _1_main_1_opaque_NodeStruct *)0;
extern int pthread_barrier_destroy(int *barrier ) ;
struct _1_calc_fibonacci_1_opaque_NodeStruct *_1_calc_fibonacci_1_opaque_list_1  =    (struct _1_calc_fibonacci_1_opaque_NodeStruct *)0;
extern int strncmp(char const   *s1 ,
                   char const   *s2 , unsigned int maxlen ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int _global_argc  =    0;
extern int pthread_cond_signal(int *cond ) ;
struct _1_mult_chars_1_opaque_NodeStruct {
   struct _1_mult_chars_1_opaque_NodeStruct *prev ;
   struct _1_mult_chars_1_opaque_NodeStruct *next ;
   int data ;
};
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int raise(int sig ) ;
extern int scanf(char const   *format  , ...) ;
char **_global_envp  =    (char **)0;
struct _1_generate_license_key_1_opaque_NodeStruct *_1_generate_license_key_1_opaque_ptr_2  =    (struct _1_generate_license_key_1_opaque_NodeStruct *)0;
struct _1_mult_chars_1_opaque_NodeStruct *_1_mult_chars_1_opaque_list_1  =    (struct _1_mult_chars_1_opaque_NodeStruct *)0;
extern int unlink(char const   *filename ) ;
struct _1_calc_fibonacci_1_opaque_NodeStruct *_1_calc_fibonacci_1_opaque_list_2  =    (struct _1_calc_fibonacci_1_opaque_NodeStruct *)0;
extern int pthread_barrier_wait(int *barrier ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_mutex_lock(int *mutex ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
struct _1_main_1_opaque_NodeStruct *_1_main_1_opaque_list_1  =    (struct _1_main_1_opaque_NodeStruct *)0;
extern void *dlsym(void *handle , char *symbol ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern void abort() ;
typedef struct _1_calc_fibonacci_1_opaque_NodeStruct *_1_calc_fibonacci_1_opaque_StructureType;
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
struct _1_mult_chars_1_opaque_NodeStruct *_1_mult_chars_1_opaque_ptr_1  =    (struct _1_mult_chars_1_opaque_NodeStruct *)0;
int main(int argc , char **argv , char **_formal_envp ) ;
extern void signal(int sig , void *func ) ;
extern void exit(int status ) ;
typedef struct _IO_FILE FILE;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern int close(int filedes ) ;
extern double log(double x ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
struct _1_mult_chars_1_opaque_NodeStruct *_1_mult_chars_1_opaque_ptr_2  =    (struct _1_mult_chars_1_opaque_NodeStruct *)0;
extern double ceil(double x ) ;
struct _1_calc_fibonacci_1_opaque_NodeStruct *_1_calc_fibonacci_1_opaque_ptr_1  =    (struct _1_calc_fibonacci_1_opaque_NodeStruct *)0;
struct _1_generate_license_key_1_opaque_NodeStruct *_1_generate_license_key_1_opaque_ptr_1  =    (struct _1_generate_license_key_1_opaque_NodeStruct *)0;
struct _1_main_1_opaque_NodeStruct *_1_main_1_opaque_ptr_2  =    (struct _1_main_1_opaque_NodeStruct *)0;
extern int fclose(void *stream ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern void perror(char const   *str ) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern long clock(void) ;
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long time(long *tloc ) ;
struct _1_main_1_opaque_NodeStruct *_1_main_1_opaque_ptr_1  =    (struct _1_main_1_opaque_NodeStruct *)0;
extern int rand() ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
struct _1_mult_chars_1_opaque_NodeStruct *_1_mult_chars_1_opaque_list_2  =    (struct _1_mult_chars_1_opaque_NodeStruct *)0;
typedef struct _1_mult_chars_1_opaque_NodeStruct *_1_mult_chars_1_opaque_StructureType;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,2), __leaf__)) strcmp)(char const   *__s1 ,
                                                                                               char const   *__s2 )  __attribute__((__pure__)) ;
typedef struct _1_generate_license_key_1_opaque_NodeStruct *_1_generate_license_key_1_opaque_StructureType;
extern double sqrt(double x ) ;
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__,
__alloc_size__(1))) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
int mult_chars(char username_char , char secret_key_char ) ;
extern int nanosleep(int *rqtp , int *rmtp ) ;
typedef struct _1_main_1_opaque_NodeStruct *_1_main_1_opaque_StructureType;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int atoi(char const   *s ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
char *generate_license_key(char *username , size_t username_len ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
int calc_fibonacci(int nth_fib_num ) ;
void megaInit(void) ;
void megaInit(void) 
{ 


  {

}
}
int calc_fibonacci(int nth_fib_num ) 
{ 
  int fib_num ;
  int first ;
  int second ;
  int i ;
  struct _1_calc_fibonacci_1_opaque_NodeStruct *p6 ;
  int r7 ;
  struct _1_calc_fibonacci_1_opaque_NodeStruct *p8 ;
  int r9 ;
  struct _1_calc_fibonacci_1_opaque_NodeStruct *p10 ;
  int _1_calc_fibonacci__BEGIN_1 ;
  int _1_calc_fibonacci__END_1 ;
  int _1_calc_fibonacci__BARRIER_2 ;

  {
  {  /* __blockattribute__(__ATOMIC__)*/ 
  _1_calc_fibonacci__BEGIN_1 = 1;
  p6 = (struct _1_calc_fibonacci_1_opaque_NodeStruct *)malloc(sizeof(struct _1_calc_fibonacci_1_opaque_NodeStruct ));
  p6->next = p6;
  p6->prev = p6;
  _1_calc_fibonacci_1_opaque_list_1 = p6;
  r9 = rand();
  p10 = (struct _1_calc_fibonacci_1_opaque_NodeStruct *)malloc(sizeof(struct _1_calc_fibonacci_1_opaque_NodeStruct ));
  p10->data = 0 * r9;
  p10->next = _1_calc_fibonacci_1_opaque_list_1->next;
  p10->prev = _1_calc_fibonacci_1_opaque_list_1;
  (_1_calc_fibonacci_1_opaque_list_1->next)->prev = p10;
  _1_calc_fibonacci_1_opaque_list_1->next = p10;
  r7 = rand();
  p8 = (struct _1_calc_fibonacci_1_opaque_NodeStruct *)malloc(sizeof(struct _1_calc_fibonacci_1_opaque_NodeStruct ));
  p8->data = 1 * r7;
  p8->next = _1_calc_fibonacci_1_opaque_list_1->next;
  p8->prev = _1_calc_fibonacci_1_opaque_list_1;
  (_1_calc_fibonacci_1_opaque_list_1->next)->prev = p8;
  _1_calc_fibonacci_1_opaque_list_1->next = p8;
  _1_calc_fibonacci_1_opaque_ptr_1 = _1_calc_fibonacci_1_opaque_list_1->next;
  _1_calc_fibonacci_1_opaque_ptr_2 = _1_calc_fibonacci_1_opaque_ptr_1;
  _1_calc_fibonacci__END_1 = 1;
  }
  _1_calc_fibonacci__BARRIER_2 = 1;

  if (nth_fib_num < 1) {
    return (-1);
  }
  fib_num = 1;
  first = 0;
  second = 1;
  i = 1;
  while (i < nth_fib_num) {
    {
    if (_1_mult_chars_1_opaque_ptr_1 == _1_mult_chars_1_opaque_ptr_2) {
      fib_num = first + second;
      first = second;
      second = fib_num;
      i ++;
    } else {
      __asm__  volatile   (".byte 0x3e,0x40":);
    }
    }
  }
  return (fib_num);
}
}
int main(int argc , char **argv , char **_formal_envp ) 
{ 
  size_t tmp ;
  size_t tmp___0 ;
  char *calculated_license_key ;
  size_t tmp___1 ;
  char *tmp___2 ;
  int tmp___3 ;
  int _BARRIER_0 ;
  struct _1_main_1_opaque_NodeStruct *p11 ;
  int r12 ;
  struct _1_main_1_opaque_NodeStruct *p13 ;
  int r14 ;
  struct _1_main_1_opaque_NodeStruct *p15 ;
  int _1_main__BEGIN_5 ;
  int _1_main__END_5 ;
  int _1_main__BARRIER_6 ;

  {
  megaInit();
  _global_argc = argc;
  _global_argv = argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = 1;
  {  /* __blockattribute__(__ATOMIC__)*/ 
  _1_main__BEGIN_5 = 1;
  p11 = (struct _1_main_1_opaque_NodeStruct *)malloc(sizeof(struct _1_main_1_opaque_NodeStruct ));
  p11->next = p11;
  p11->prev = p11;
  _1_main_1_opaque_list_1 = p11;
  r14 = rand();
  p15 = (struct _1_main_1_opaque_NodeStruct *)malloc(sizeof(struct _1_main_1_opaque_NodeStruct ));
  p15->data = 0 * r14;
  p15->next = _1_main_1_opaque_list_1->next;
  p15->prev = _1_main_1_opaque_list_1;
  (_1_main_1_opaque_list_1->next)->prev = p15;
  _1_main_1_opaque_list_1->next = p15;
  r12 = rand();
  p13 = (struct _1_main_1_opaque_NodeStruct *)malloc(sizeof(struct _1_main_1_opaque_NodeStruct ));
  p13->data = 1 * r12;
  p13->next = _1_main_1_opaque_list_1->next;
  p13->prev = _1_main_1_opaque_list_1;
  (_1_main_1_opaque_list_1->next)->prev = p13;
  _1_main_1_opaque_list_1->next = p13;
  _1_main_1_opaque_ptr_1 = _1_main_1_opaque_list_1->next;
  _1_main_1_opaque_ptr_2 = _1_main_1_opaque_ptr_1;
  _1_main__END_5 = 1;
  }
  _1_main__BARRIER_6 = 1;

  {
  if (_1_mult_chars_1_opaque_ptr_1 == _1_mult_chars_1_opaque_ptr_2) {

  } else {
    r14 = mult_chars((char)6, (char)4);
  }
  if (argc != 3) {
    printf((char const   */* __restrict  */)"Required Arguments: Username, License-Key\n");
    return (-1);
  }
  }
  tmp = strlen((char const   *)*(argv + 1));
  if (tmp < 3UL) {
    printf((char const   */* __restrict  */)"Username needs to be at least 3 Characters long!\n");
    return (-2);
  }
  tmp___0 = strlen((char const   *)*(argv + 2));
  if (tmp___0 != 10UL) {
    printf((char const   */* __restrict  */)"License-key needs to be 10 Characters long!\n");
    return (-3);
  }
  tmp___1 = strlen((char const   *)*(argv + 1));
  tmp___2 = generate_license_key(*(argv + 1), tmp___1);
  calculated_license_key = tmp___2;
  tmp___3 = strcmp((char const   *)calculated_license_key, (char const   *)*(argv + 2));
  if (tmp___3 == 0) {
    printf((char const   */* __restrict  */)"Username and License-key match!\n");
    free((void *)calculated_license_key);
    return (0);
  } else {
    printf((char const   */* __restrict  */)"License key doesn\'t match username!\n");
    printf((char const   */* __restrict  */)"Generated License Key: %s\n", calculated_license_key);
    free((void *)calculated_license_key);
    return (-4);
  }
}
}
char *generate_license_key(char *username , size_t username_len ) 
{ 
  char key_alphabet[63] ;
  char secret_key[41] ;
  int key_length ;
  char *license_key ;
  void *tmp ;
  int i ;
  int username_char_pos ;
  int tmp___0 ;
  int secret_key_char_pos ;
  int tmp___1 ;
  char username_char ;
  char secret_key_char ;
  size_t tmp___2 ;
  int tmp___3 ;
  size_t tmp___4 ;
  struct _1_generate_license_key_1_opaque_NodeStruct *p18 ;
  int r19 ;
  struct _1_generate_license_key_1_opaque_NodeStruct *p20 ;
  int r21 ;
  struct _1_generate_license_key_1_opaque_NodeStruct *p22 ;
  int r23 ;
  struct _1_generate_license_key_1_opaque_NodeStruct *p24 ;
  int r25 ;
  struct _1_generate_license_key_1_opaque_NodeStruct *p26 ;
  int _1_generate_license_key__BEGIN_3 ;
  int _1_generate_license_key__END_3 ;
  int _1_generate_license_key__BARRIER_4 ;

  {
  {  /* __blockattribute__(__ATOMIC__)*/ 
  _1_generate_license_key__BEGIN_3 = 1;
  p18 = (struct _1_generate_license_key_1_opaque_NodeStruct *)malloc(sizeof(struct _1_generate_license_key_1_opaque_NodeStruct ));
  p18->next = p18;
  p18->prev = p18;
  _1_generate_license_key_1_opaque_list_1 = p18;
  r25 = rand();
  p26 = (struct _1_generate_license_key_1_opaque_NodeStruct *)malloc(sizeof(struct _1_generate_license_key_1_opaque_NodeStruct ));
  p26->data = 0 * r25;
  p26->next = _1_generate_license_key_1_opaque_list_1->next;
  p26->prev = _1_generate_license_key_1_opaque_list_1;
  (_1_generate_license_key_1_opaque_list_1->next)->prev = p26;
  _1_generate_license_key_1_opaque_list_1->next = p26;
  r23 = rand();
  p24 = (struct _1_generate_license_key_1_opaque_NodeStruct *)malloc(sizeof(struct _1_generate_license_key_1_opaque_NodeStruct ));
  p24->data = 1 * r23;
  p24->next = _1_generate_license_key_1_opaque_list_1->next;
  p24->prev = _1_generate_license_key_1_opaque_list_1;
  (_1_generate_license_key_1_opaque_list_1->next)->prev = p24;
  _1_generate_license_key_1_opaque_list_1->next = p24;
  r21 = rand();
  p22 = (struct _1_generate_license_key_1_opaque_NodeStruct *)malloc(sizeof(struct _1_generate_license_key_1_opaque_NodeStruct ));
  p22->data = 2 * r21;
  p22->next = _1_generate_license_key_1_opaque_list_1->next;
  p22->prev = _1_generate_license_key_1_opaque_list_1;
  (_1_generate_license_key_1_opaque_list_1->next)->prev = p22;
  _1_generate_license_key_1_opaque_list_1->next = p22;
  r19 = rand();
  p20 = (struct _1_generate_license_key_1_opaque_NodeStruct *)malloc(sizeof(struct _1_generate_license_key_1_opaque_NodeStruct ));
  p20->data = 3 * r19;
  p20->next = _1_generate_license_key_1_opaque_list_1->next;
  p20->prev = _1_generate_license_key_1_opaque_list_1;
  (_1_generate_license_key_1_opaque_list_1->next)->prev = p20;
  _1_generate_license_key_1_opaque_list_1->next = p20;
  _1_generate_license_key_1_opaque_ptr_1 = _1_generate_license_key_1_opaque_list_1->next;
  _1_generate_license_key_1_opaque_ptr_2 = _1_generate_license_key_1_opaque_ptr_1;
  _1_generate_license_key_1_opaque_ptr_2 = _1_generate_license_key_1_opaque_ptr_2->next;
  _1_generate_license_key__END_3 = 1;
  }
  _1_generate_license_key__BARRIER_4 = 1;
  key_alphabet[0] = (char )'A';
  key_alphabet[1] = (char )'B';
  key_alphabet[2] = (char )'C';
  key_alphabet[3] = (char )'D';
  key_alphabet[4] = (char )'E';
  key_alphabet[5] = (char )'F';
  key_alphabet[6] = (char )'G';
  key_alphabet[7] = (char )'H';
  key_alphabet[8] = (char )'I';
  key_alphabet[9] = (char )'J';
  key_alphabet[10] = (char )'K';
  key_alphabet[11] = (char )'L';
  key_alphabet[12] = (char )'M';
  key_alphabet[13] = (char )'N';
  key_alphabet[14] = (char )'O';
  key_alphabet[15] = (char )'P';
  key_alphabet[16] = (char )'Q';
  key_alphabet[17] = (char )'R';
  key_alphabet[18] = (char )'S';
  key_alphabet[19] = (char )'T';
  key_alphabet[20] = (char )'U';
  key_alphabet[21] = (char )'V';
  key_alphabet[22] = (char )'W';
  key_alphabet[23] = (char )'X';
  key_alphabet[24] = (char )'Y';
  key_alphabet[25] = (char )'Z';
  key_alphabet[26] = (char )'a';
  key_alphabet[27] = (char )'b';
  key_alphabet[28] = (char )'c';
  key_alphabet[29] = (char )'d';
  key_alphabet[30] = (char )'e';
  key_alphabet[31] = (char )'f';
  key_alphabet[32] = (char )'g';
  key_alphabet[33] = (char )'h';
  key_alphabet[34] = (char )'i';
  key_alphabet[35] = (char )'j';
  key_alphabet[36] = (char )'k';
  key_alphabet[37] = (char )'l';
  key_alphabet[38] = (char )'m';
  key_alphabet[39] = (char )'n';
  key_alphabet[40] = (char )'o';
  key_alphabet[41] = (char )'p';
  key_alphabet[42] = (char )'q';
  key_alphabet[43] = (char )'r';
  key_alphabet[44] = (char )'s';
  key_alphabet[45] = (char )'t';
  key_alphabet[46] = (char )'u';
  key_alphabet[47] = (char )'v';
  key_alphabet[48] = (char )'w';
  key_alphabet[49] = (char )'x';
  key_alphabet[50] = (char )'y';
  key_alphabet[51] = (char )'z';
  key_alphabet[52] = (char )'0';
  key_alphabet[53] = (char )'1';
  key_alphabet[54] = (char )'2';
  key_alphabet[55] = (char )'3';
  key_alphabet[56] = (char )'4';
  key_alphabet[57] = (char )'5';
  key_alphabet[58] = (char )'6';
  key_alphabet[59] = (char )'7';
  key_alphabet[60] = (char )'8';
  key_alphabet[61] = (char )'9';
  key_alphabet[62] = (char )'\000';
  secret_key[0] = (char )'b';
  secret_key[1] = (char )'1';
  secret_key[2] = (char )'9';
  secret_key[3] = (char )'d';
  secret_key[4] = (char )'b';
  secret_key[5] = (char )'b';
  secret_key[6] = (char )'c';
  secret_key[7] = (char )'8';
  secret_key[8] = (char )'a';
  secret_key[9] = (char )'7';
  secret_key[10] = (char )'c';
  secret_key[11] = (char )'7';
  secret_key[12] = (char )'5';
  secret_key[13] = (char )'7';
  secret_key[14] = (char )'1';
  secret_key[15] = (char )'f';
  secret_key[16] = (char )'1';
  secret_key[17] = (char )'8';
  secret_key[18] = (char )'1';
  secret_key[19] = (char )'5';
  secret_key[20] = (char )'5';
  secret_key[21] = (char )'d';
  secret_key[22] = (char )'9';
  secret_key[23] = (char )'0';
  secret_key[24] = (char )'2';
  secret_key[25] = (char )'0';
  secret_key[26] = (char )'9';
  secret_key[27] = (char )'0';
  secret_key[28] = (char )'1';
  secret_key[29] = (char )'6';
  secret_key[30] = (char )'3';
  secret_key[31] = (char )'5';
  secret_key[32] = (char )'2';
  secret_key[33] = (char )'9';
  secret_key[34] = (char )'7';
  secret_key[35] = (char )'d';
  secret_key[36] = (char )'1';
  secret_key[37] = (char )'0';
  secret_key[38] = (char )'f';
  secret_key[39] = (char )'8';
  secret_key[40] = (char )'\000';
  key_length = 10;
  tmp = malloc((size_t )(key_length + 1));
  license_key = (char *)tmp;
  i = 0;
  while (i < key_length) {
    tmp___0 = calc_fibonacci(i + 2);
    username_char_pos = tmp___0;
    tmp___1 = calc_fibonacci(i + 3);
    secret_key_char_pos = tmp___1;
    username_char = *(username + (unsigned long )username_char_pos % username_len);
    tmp___2 = strlen((char const   *)(secret_key));
    secret_key_char = secret_key[secret_key_char_pos % (int )tmp___2];
    tmp___3 = mult_chars(username_char, secret_key_char);
    tmp___4 = strlen((char const   *)(key_alphabet));
    *(license_key + i) = key_alphabet[(unsigned long )tmp___3 % tmp___4];
    i ++;
  }
  *(license_key + key_length) = (char )'\000';
  {
  if (_1_mult_chars_1_opaque_ptr_1 == _1_mult_chars_1_opaque_ptr_2) {
    return (license_key);
  } else {
    __asm__  volatile   (".byte 0x39,0x42":);
  }
  }
}
}
int mult_chars(char username_char , char secret_key_char ) 
{ 
  struct _1_mult_chars_1_opaque_NodeStruct *p3 ;
  int r4 ;
  struct _1_mult_chars_1_opaque_NodeStruct *p5 ;
  int r6 ;
  struct _1_mult_chars_1_opaque_NodeStruct *p7 ;
  int _1_mult_chars__BEGIN_7 ;
  int _1_mult_chars__END_7 ;
  int _1_mult_chars__BARRIER_8 ;

  {
  {  /* __blockattribute__(__ATOMIC__)*/ 
  _1_mult_chars__BEGIN_7 = 1;
  p3 = (struct _1_mult_chars_1_opaque_NodeStruct *)malloc(sizeof(struct _1_mult_chars_1_opaque_NodeStruct ));
  p3->next = p3;
  p3->prev = p3;
  _1_mult_chars_1_opaque_list_1 = p3;
  r6 = rand();
  p7 = (struct _1_mult_chars_1_opaque_NodeStruct *)malloc(sizeof(struct _1_mult_chars_1_opaque_NodeStruct ));
  p7->data = 0 * r6;
  p7->next = _1_mult_chars_1_opaque_list_1->next;
  p7->prev = _1_mult_chars_1_opaque_list_1;
  (_1_mult_chars_1_opaque_list_1->next)->prev = p7;
  _1_mult_chars_1_opaque_list_1->next = p7;
  r4 = rand();
  p5 = (struct _1_mult_chars_1_opaque_NodeStruct *)malloc(sizeof(struct _1_mult_chars_1_opaque_NodeStruct ));
  p5->data = 1 * r4;
  p5->next = _1_mult_chars_1_opaque_list_1->next;
  p5->prev = _1_mult_chars_1_opaque_list_1;
  (_1_mult_chars_1_opaque_list_1->next)->prev = p5;
  _1_mult_chars_1_opaque_list_1->next = p5;
  _1_mult_chars_1_opaque_ptr_1 = _1_mult_chars_1_opaque_list_1->next;
  _1_mult_chars_1_opaque_ptr_2 = _1_mult_chars_1_opaque_ptr_1;
  _1_mult_chars__END_7 = 1;
  }
  _1_mult_chars__BARRIER_8 = 1;

  {
  if (_1_mult_chars_1_opaque_ptr_1 != _1_mult_chars_1_opaque_ptr_2) {

  } else {
    return ((int )username_char * (int )secret_key_char);
  }
  }
}
}
